### PR TITLE
fix-for-twitter-share-issue

### PR DESCRIPTION
**Pull request by abhijithvijayan**

### CODE REVIEW

**Comment by abhijithvijayan** [comment]
Encoding this url and twitter intending worked. But it would be better if using a short url like https://kutt.it to shorten the link first then sharing it as a tweet.

firefox_2018-07-08_09-20-55


https://itty.bitty.site/#/?XQAAAAJdYgAAAAAAAAAuDwoD4fA6UK6YUKOtMWHja/kspk4+ujl6CiaZSrXF4OXSZzzKqk6e/jY+S59976kSvpmgX98pAGJ17jU9K7xGMe23rfwiFW5DTtVBuegoQ+c18uN9+aJfiLCm8+CARLQitrTglZaifSu6BKmWuc2lgcb3k9zY/VzQRENqR1/NTRU6sWXg7ih0m6qFPDg7KOzOBFYkfJQfnkXn+/RvfOFmOWuZtfzB+bBdFLXxA9unMibkSsoUVqXPrUq+rPAz77sm/G20lRqL7PfoT25ith6ICSKG+MhkX44uohNtsMF6S+BUP8gA5zyrt9j/ftjGoXfLPLxAdrHPmvvcABLsbKoGGJpp+J+i1zsYwON6zhrz/Rzfw4hs2EZ0gELNddrq8Jmj4nB9D1oFtPtCyChNlR9Q7Lx76pV1d5739eWxfJiUxG0kj7a6sjsvewHPHb6Yl2L3Mvp9IZoqpDKjO2matia3qWW4+iw8FJR2aUpWZtCupBQlTKbQ+2Yxv1axIgJzf+5kotBhGmF/kKScIVqGxQMksfZhqSJK8okzPYpKOskZI/FKm5qZDDaorm5tCHs/fFvQNc1ajs0xgFRk+jKUQxFewvbpka9XJjZtgU4AdtOLcId6nqSxSzHWdaZzbcCUYsXvoRbjBvGv1MaDCHV/bVkfWMuDclL2psLDM+TaBNqyRYHhBdv4QfOKMe2avYMtgMjhzUg9uxwIQhTNsWK6Sfl74g14t1KyyO99YSwR2MCrxt61agZHy2yBjjTuhY8fE8vAbS0noc7Zu6pKeaaLqHj9odYmbHE5rmBwDUrihXQ0l4a4hRwBsaSWgSF2PTc+qLXoW9vhrPjB14AYJmVon+iiBvzuDb5uDmpn6aCO1avq+1pZKjqrZUVzrsAzDJJZ7wc5mpBRmju5f1Tclc/DU0RRMd4gp8mzJRIhAdI+KhFIhW5UDNmrlIHzzCW8BlxnGyiW4Of2eljUm9uHkDw3uLDgEyNax1gmnMtxcFai8RFg8W1+zkc9SLrPgHQUcxQVHFMxrBM1vA/9gWMHdp1tWI/CEVwAmB5covo/YF2dfrO3Wq0m+h4Lx4wgVYODM1oend9mjlFUFcRL8KCXhqURjltM2AQCmrOo+IEwaQzwaBH/KRfArAATlMQopb7XgJIZX9vQwwvU6apSmJu96cHhkmCZdTADKChwEC9ioJAfYj1fdNOU4pacxNE79V69YbMx5xMxL10eDh9PnXhXmypzD0w2FhSkUWpXJfjOrKROzTVosPhFA3a5Pt2z/ZscIr2NsHDMTOuxL+DXO3ztOh9JWW0eQw2Y85kyQoWhIYMdFpM0QmMdFGVQ/+5cpNmFPkIcyNrB2/f+Vf6QJ/t+1wYaeCMA6H9AV5AQFfzng4vMk/5zwIYrsYVST+3FXwg3eAaV0AGucxFTbgemKexw3Eui8WL486vHip3CzD38KoY0arPxT52rIEi6GrgmGmUzXoYD7SBrcwvbqCbzVRM0ymcJ3+QUMlm1KJbt0QmLsGvhEp7SRDG/sT30LvZdnNH4wRHaQ5eOq9ump6BqGPkMdvS66fennvn35/mzBpFT1458S+TRAXo5nACK2sXFc/8xsbKqZZM795kBi7NfZE/8CvTn0LQvSUEccPMv6VhtgDP+prSB+n1sw9C1Czjtbw29t3Qf89zstyA2sv1WcygNUlfpTu/LY07kieE386TLbnp+kzErS5sjQFv3zKPlAI1kR/USlyClOlGG8nTCcfRm8CFYxL7IUiS0qTQJDRY88hiK/mU2vyd/mKzJ0JdeRW4rKrc0rqeZDgPyu91NL5+hLrnI8Nfz+nPTDyvoU1BNjEWm4ndBQKa/q6j1jZoVfqaNE1uU3Pn2MkV57291JUsiuHgmnIiu+zh1MIN9ctM2op617jeCseU0cVtn+RKEoAgCRMpdoHYqPtfhbsE/IRjdRQCs/aM4BFe5J6M7brH0dqnoUs6yXH7RsOSci3G4maC+RuOptC/CIhumRSHAigkt8sWFIHwyev2m6aozfX0rVP6+2gEBBPnkWHFWtgRWdBzi5qMmIYTWQ24NVskJ5bA/LJZRx0nUga1jjEPR7Xjw7sKWeHHmdUefKvqDyKQdMIpWPZau1fpYjJsmG0P6woWxx0EB9jimps/x3yDtNokcWmfPNn6UYoWhLAzmy5vS8dBLtctJknz1BS1tnTo98B68y5Q/sdePS/0Jeuuo+eiUewNAJSvRWzRFQvuWDNR2HVo23D07wcuCVZhVImv5fOAu52FJ9deNi4n586Ra41nQvv0eoUt5lO0m/eTdyVOikFrheKuwQ0VJpDxN+Q6ASKXDtz+LpEe5wFfC7qBOw2I3CGmc9vVXRkgX8l12ld4PsIPtgycEyYq5kyvtS2lNzq19SAUGiIpVGg8fP0OOc4LWnb57+IKsyC+aOXkWSQMCXYP2xc4UJuL/tfLuBOcU2u9NXVgGTAqHXU5IPypCKrYnYkX6d1x3lcUgzkwF95O8jk2uigJ6Xm1ZX7MdWF5H2ZDJFViJJbld9bsT2+AriXCvrJERh7dqJy/+BPIoSvdJJUp3Gndc8IbJT4gplJUSTyflO6kaArKWsSkMT7zxN7ghVnfQzVWsVejy8VJwT3Asg3L0/8TBfkiQOHbv3AByXvYXL06N7QOkqkgumPw8gS2K06x8+yMnrC0lFYgySJkr/W/9lq/6LM5Ffb/vwMjFEdY2aLpS8xBHfL4oCJArXP4YhQE5IqM70oGyVNsoCt3zG1YZWs+qljbLbCJ/stEqnlWdJEghpdmKwPc6UvXRivcYW5c+rH4ICYCewal7SuxmOAyci0QUcLxnNDRpJog6T+levqmmw0+sRG//mo2Ao/Y+uzLx+YxOlNQ7HEUCLapjU3O5X8lKUBM9puj78yOoeTCbsIJz4vznGH+ZyM+jJ4kJjfaIL6JPtO/Ej8TlGJ0cJAjJzaTYm1JlzKpaUfalDBK77a/0Ioda7enapuARXN37/VZ2y1o4olLCwzOlgkbKUEQMyj9kt34c6EAwaaRwQo+msql+KAp4q68w+tTtA9vaC3JXQjLFbvQ3klFKzvPL/S5p1gYxVhn8I9/HLACKAbbxwlqPb//I9tBx

**Comment by alcor** [comment]
Twitter has a built in link-shortener, which should be active. I was just seeing inconsistent behavior from it.

**Comment by abhijithvijayan** [comment]
But I didn't face anything after url encoding

Twitter intended the url to the post and successfully posted.

Thanks

**Comment by abhijithvijayan** [comment]
Fixed

**Pull request closed without merging**
