### PR TITLE
Consistent CSS code format(indentation and alignment fix)

### PR DESCRIPTION
**Pull request by prashant-andani**
Consistent CSS code format(indentation and alignment fix)

### CODE REVIEW

**Comment by alcor** [comment]
Which tool did you use to do the css formatting? I'll run it, but my version is sufficiently changed that I can't do the merge effectively.

I'd rather not reformat the js, as much of it is already minified.

**Comment by prashant-andani** [comment]
I have used Prettier http://prettier.io/..
We could use webpack or parcel to bundle (minify and everything)
I feel the code should be more readable while coding and let the tools take care of minifying...

**Comment by alcor** [comment]
I'll look into webpack and parcel. I started breaking out index.js and index.css, since that is the one I care about the most. Thank you for the pointers :)

**Comment by alcor** [comment]
Hmm. The main challenge I have is wanting to compile to a single source file (to reduce web requests). Parcel looks like it wants to create a set of distribution versions, but still linked separately.
For now, I'm gonna embed the minified versions manually, bu I'll keep trying.

**Pull request closed without merging**
